### ISSUE TITLE
@Produces({MediaType.APPLICATION_XML}) error

### ISSUE THREAD

**Issue by yale8848** [zandero/rest.vertx#10]
```
    @GET
    @Path("/h1")
    @Produces({MediaType.APPLICATION_XML})
    public Response h1(){
        User u = new User();
        u.setPassword("p");
        u.setName("a");
        return Response.ok(u).build();
    }
```

This page contains the following errors:
error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.

Why this happen?

**Comment by drejc** [comment]
OK ... I have not enough information to debug this ... 

- do you have a writer associated with this media type? ... XML by default has no associated writer
- do you have a Response implementation associated ?
- can the User object be deserialized ... ?

For instance ... create a XmlWriter ... 
```java
public class MyXmlWriter implements HttpResponseWriter<User> {

	@Override
	public void write(User result, HttpServerRequest request, HttpServerResponse response) {

		response.end("<u name=\"" + result.name  + "\" />");
	}
}
```

Associate the writer with your mime type ... method
`RestRouter.getWriters().register(MediaType.APPLICATION_XML_TYPE, MyXmlWriter.class);`

or
```java
@GET
@Path("/h1")
@Produces({MediaType.APPLICATION_XML})
@ResponseWriter(MyXmlWriter.class)
public Response h1() {
	User u = new User("test");
	return Response.ok(u).build();
}
```

**Comment by yale8848** [comment]
It can work. Thank you very much. 👍
