### ISSUE TITLE
IllegalArgumentException when register ExceptionHandler

### ISSUE THREAD

**Issue by kruckerr** [zandero/rest.vertx#102]
I registered a customized exception handler by using RestRouter.getExceptionHandlers().register(exceptionHandlerClass). I have several vertx unit tests, that starts the http server. The first test runs fine, but all others fail due to an IllegalArgumentException when it registers my customized exception handler.

**Comment by drejc** [comment]
Can you paste a code snippet of you unit test ... hard to tell what is wrong.
You can also take a peek at [/RouteExceptionHandlerTest.java](https://github.com/zandero/rest.vertx/blob/master/src/test/java/com/zandero/rest/RouteExceptionHandlerTest.java) where those type of situations are tested.

**Comment by kruckerr** [comment]
This is my test class. Just running this tests work fine when I start the server before running all tests. Initially, I startet the server before each test. Then I had the issue. But I have a second test class, that starts the server as well and when I run the tests of both test classes, the tests of the second classes will fail. The problem seem to be the static member "forge" in RestRouter, that returns the the ExceptionHandlerCache. Due to this member is static, it will remember the ExceptionHandlers from before. Or do I have a possibility to clean up this ExceptionHandlerCache after the test?

`@ExtendWith({VertxExtension.class})
class WebServerVerticleTest {

    public static final int TEST_SERVER_PORT = 8181;
    public static final String TEST_SERVER_HOST = "localhost";

    @BeforeAll
    static void deployVerticle(Vertx vertx, VertxTestContext testContext) {
        List<IRestController> activeControllers = Arrays.asList(new PrivateHelloRestController());
        SocketHandler socketHandler = new SocketHandler(vertx, null);
        vertx.deployVerticle(new WebServerVerticle(TEST_SERVER_PORT, null, socketHandler).with(activeControllers), testContext.succeeding(id -> testContext.completeNow()));
    }

    @Test
    @Timeout(timeUnit = TimeUnit.SECONDS, value = 2)
    void whenCallHello_thenGetResponse(Vertx vertx, VertxTestContext testContext) {
        WebClient webClient = WebClient.create(vertx);
        webClient.get(TEST_SERVER_PORT, TEST_SERVER_HOST, "/api/hello").send(ar -> {
            if (ar.succeeded()) {
                HttpResponse<Buffer> response = ar.result();
                assertThat(response.statusCode()).isEqualTo(200);
                assertThat(response.bodyAsString()).isEqualTo("Hello from Vert.x");
                testContext.completeNow();
            } else {
                testContext.failNow(ar.cause());
            }
        });
    }

    @Test
    @Timeout(timeUnit = TimeUnit.SECONDS, value = 2)
    void whenRequestIsUsedAndResponseIsModfied(Vertx vertx, VertxTestContext testContext) {
        WebClient webClient = WebClient.create(vertx);
        webClient.get(TEST_SERVER_PORT, TEST_SERVER_HOST, "/api/context").send(ar -> {
            if (ar.succeeded()) {
                HttpResponse<Buffer> response = ar.result();
                assertThat(response.statusCode()).isEqualTo(201);
                assertThat(response.bodyAsString()).isEqualTo("/api/context");
                testContext.completeNow();
            } else {
                testContext.failNow(ar.cause());
            }
        });
    }

    @Test
    @Timeout(timeUnit = TimeUnit.SECONDS, value = 2)
    void whenCallPrivateHello_thenGetResponse(Vertx vertx, VertxTestContext testContext) {
        WebClient webClient = WebClient.create(vertx);
        webClient.get(TEST_SERVER_PORT, TEST_SERVER_HOST, "/private/hello").bearerTokenAuthentication(generateToken()).send(ar -> {
            if (ar.succeeded()) {
                HttpResponse<Buffer> response = ar.result();
                assertThat(response.statusCode()).isEqualTo(200);
                assertThat(response.bodyAsString()).isEqualTo("Private hello from Vert.x");
                testContext.completeNow();
            } else {
                testContext.failNow(ar.cause());
            }
        });
    }

    @Test
    @Timeout(timeUnit = TimeUnit.SECONDS, value = 2)
    void whenCallPrivateHelloWithoutToken_thenGetError(Vertx vertx, VertxTestContext testContext) {
        WebClient webClient = WebClient.create(vertx);
        webClient.get(TEST_SERVER_PORT, TEST_SERVER_HOST, "/private/hello").send(ar -> {
            if (ar.succeeded()) {
                HttpResponse<Buffer> response = ar.result();
                assertThat(response.statusCode()).isEqualTo(401);
                assertThat(response.bodyAsString()).isNullOrEmpty();
                testContext.completeNow();
            } else {
                testContext.failNow(ar.cause());
            }
        });
    }

    private String generateToken() {
        JsonObject data = new JsonObject();
        data.put("sub", "the.user");
        data.put("id", 2);
        data.put("permissions", Arrays.asList("Admin"));
        JWTOptions options = new JWTOptions();
        options.setExpiresInSeconds(10);
        JWTAuth authProvider = JWTAuth.create(Vertx.vertx(), new JWTAuthOptions()
                .addPubSecKey(new PubSecKeyOptions()
                        .setAlgorithm("HS256")
                        .setPublicKey("93C7Z(I2k§h5\"BR1lHqH3jsZG5H8.D§P[!{c.&u1h!q*Ob3D!u-4bvX0iNL2+iP:7QFJ2L94Nv>*##t9")
                        .setSymmetric(true)
                ));
        return authProvider.generateToken(data, options);
    }
}`

**Comment by drejc** [comment]
You are correct handlers, readers, writers ... etc. are all cached once registered. This is a feature of the library.
If you take a look at my base test class: [VertxTest](https://github.com/zandero/rest.vertx/blob/76b2546e733f0d24bda2ef2a346cb00d98ee7d63/src/test/java/com/zandero/rest/VertxTest.java#L15)

you will see that I have a  before() method that cleans all caches.

```java
public static void before() {

        vertx = Vertx.vertx();
        vertxTestContext = new VertxTestContext();

        // clear all registered writers or reader and handlers
        RestRouter.getReaders().clear();
        RestRouter.getWriters().clear();
        RestRouter.getExceptionHandlers().clear();
        RestRouter.getContextProviders().clear();

        // clear
        RestRouter.validateWith((Validator) null);
        RestRouter.injectWith((InjectionProvider) null);

        client = WebClient.create(vertx);
    }
```

All my tests are extended from this VertxTest class and on @BeforeAll I call the **before()** method cleaning everything up.  
I suggest that you do something similar.

**Comment by kruckerr** [comment]
That's fine for me. I will do so as well. Thank you.

**Comment by kruckerr** [comment]
The last release is already some time ago and there are many useful commits in the meantime. What are your plans. Are you going to create a release soon? And do you have plans to migrate to Vert.x 4?

**Comment by drejc** [comment]
The next release will be coming soon, I'm currently in the process of migrating to Vert.x 4 as they are some breaking changes. So stay tuned.
