### ISSUE TITLE
Response head already sent

### ISSUE THREAD

**Issue by dariolicci** [zandero/rest.vertx#109]
Hi,
I am working with 0.9.0 version with vert.x 3, and the follow code generate this error:
IllegalStateException@151 "java.lang.IllegalStateException: Response head already sent" 

    @POST
    public void post(@Context HttpServerResponse response, @Context Vertx vertx, JsonObject user) {
        vertx.eventBus().request(UserService.EVENT_ADDRESS_USER_SERVICE_SAVE,  user, replyHandler -> {
            if (!replyHandler.succeeded()) { 
                response.setStatusCode(400);
                response.end(replyHandler.cause().getMessage());
            } else {
                response.setStatusCode(200);
                response.end( ((JsonObject)replyHandler.result().body()).toBuffer());
            } 
        });
    }

How can I manage the closure of the response myself?

regards
Dario

**Comment by drejc** [comment]
Probably a default response writer was assigned (if you have not assigned one yourself)?

In order to handle the response yourself you need to create your own HttpResponseWriter where the response is not altered, because you are handling the response inside the eventbus reply handler.

... but a nicer solution would be ... 

to make the result of the eventBus() operation the return value of the REST post() method.
The result is then handled by the associated HttResponseWriter ...

**Comment by dariolicci** [comment]
Hi Andrej,

I change my code:

    @POST
    @ResponseWriter(AsyncResponseWriter.class)
    public HttpServerResponse post(@Context HttpServerResponse response, @Context Vertx vertx, JsonObject user) {
        vertx.eventBus().request(UserService.EVENT_ADDRESS_USER_SERVICE_SAVE,  user, replyHandler -> {
            if (!replyHandler.succeeded()) { 
                response.setStatusCode(400);
                response.end(replyHandler.cause().getMessage());
            } else {
                response.end( ((JsonObject)replyHandler.result().body()).toBuffer());
            } 
        });
        return response;
    }

My AsyncResponseWriter not close the response, but the response is still closed by this class RestRouter.class line 712:
		// finish if not finished by writer
		// and is not an Async REST (Async RESTs must finish responses on their own)
		if (!definition.isAsync() && !response.ended()) {
			response.end();
		}

How I can set definition.isAsync() to true?

thanks
Dario

**Comment by drejc** [comment]
You REST method needs to return an Future / Promise in order to be recognized as async.
See: [Async request]( https://github.com/zandero/rest.vertx#async)

**Comment by dariolicci** [comment]
Hi Andrej,
I find this code

    /**
     * @param returnType of REST method
     * @return true if async operation, false otherwise (blocking operation)
     */
    static boolean isAsync(Class<?> returnType) {
        return checkIfCompatibleTypes(returnType, Future.class, Promise.class);
    }

Yes I return a Promise

thanks
Dario

**Comment by drejc** [comment]
Can you give me the complete snippet ... your REST endpoint and the Writer implementation. Hard to tell from the description alone / or better jet ... if you can write a unit test

**Comment by dariolicci** [comment]
sure as soon as I can make it work I send you the writer and the endpoint

**Comment by dariolicci** [comment]
Hi Andrej,
this is the Writer:

@Produces("application/json")        // content-type header
// @Header("X-Status: I'm a dummy")    // additional static headers
public class AsyncResponseWriter implements HttpResponseWriter<Promise<JsonObject>> {

    @Override
    public void write(Promise<JsonObject> result, HttpServerRequest request, HttpServerResponse response) throws Throwable {
        System.out.println("AsyncResponseWriter");    
        result.future()
            .onFailure(err -> onFailureHandler(err, response))
            .onSuccess(res -> onSuccessHandler(res, response));
    }

    private void onFailureHandler(Throwable err, HttpServerResponse response) {
        response.setStatusCode(400);
        response.end(err.getMessage());
    }

    private void onSuccessHandler(JsonObject res, HttpServerResponse response) {
        response.end(res.toBuffer());
    }

    
    
}

and this id endpoint:
    @POST
    @ResponseWriter(AsyncResponseWriter.class)
    public Promise<JsonObject> post(@Context Vertx vertx, JsonObject user) {
        Promise<JsonObject> promise = Promise.promise();
        vertx.eventBus().request(UserService.EVENT_ADDRESS_USER_SERVICE_SAVE,  user, replyHandler -> {
            if (!replyHandler.succeeded()) { 
                promise.fail(replyHandler.cause());
            } else {
                // promise.complete();
                promise.complete((JsonObject)replyHandler.result().body());
            } 
        });
        return promise;
    }

but the result is "POST /user - Response type: 'class io.vertx.core.json.JsonObject' not matching writer type: 'io.vertx.core.Promise<io.vertx.core.json.JsonObject>' in: 'class it.dl.eolo.verticle.httpserver.AsyncResponseWriter'!"

it does not work as I expect.

**Comment by dariolicci** [comment]
Hi Andrej,
not using my writer works, than only with this:

    @POST
    public Promise<JsonObject> post(@Context Vertx vertx, JsonObject user) {
        Promise<JsonObject> promise = Promise.promise();
        vertx.eventBus().request(UserService.EVENT_ADDRESS_USER_SERVICE_SAVE,  user, replyHandler -> {
            if (!replyHandler.succeeded()) { 
                promise.fail(replyHandler.cause());
            } else {
                // promise.complete();
                promise.complete((JsonObject)replyHandler.result().body());
            } 
        });
        return promise;
    }

**Comment by drejc** [comment]
Hi @dariolicci  ... I have added a simple unit test to demonstrate what I think you are trying to achieve ... check out: TestIssue109Rest / with Issue109Test ... hope this clears things up.
