### ISSUE TITLE
Possibility to add Patch as method

### ISSUE THREAD

**Issue by jsirach** [zandero/rest.vertx#11]
Hi good evening!

Do you think there is a possibility to add the http PATCH method to your library?

Thanks and cheers,
John.

**Comment by drejc** [comment]
Sure ... wil be added in the next release.
Somehow I have missed this one.

**Comment by jsirach** [comment]
Thanks,

Sorry for the late response, also thank you for adding TRACE!

I will wait for the 0.8.1 release to maven,

Cheers!

**Comment by drejc** [comment]
The 0.8.1 release will take a while (revamping some code) ... so in the meantime just build yourself a version locally.

**Comment by jsirach** [comment]
Ok i will, thanks.

You maybe got some estimate or is the timeline like "When it's done" ?

Cheers!

**Comment by drejc** [comment]
You know what I can build a intermediate version ... and leave the big one for later ... will do a 0.8.1-beta ... or something ... just need to test some things before releasing ... 
as I don't have much time doing the big 0.8.1 release.

**Comment by jsirach** [comment]
Very much appreciated! 

But, if you don't make it, you don't make it ;)

Cheers!

**Comment by drejc** [comment]
Patch method is now "officialy" supported in revision 0.8.1 !

**Comment by jsirach** [comment]
Awesome!

I should get the 0.8.1-BETA release from maven?

P.S. Nice stuff in this release

**Comment by drejc** [comment]
Go for 0.8.1, beta was a test release.

**Comment by jsirach** [comment]
Thanks,

much appreciated.
