### ISSUE TITLE
java 17 compatibility (TypeVariableImpl)

### ISSUE THREAD

**Issue by jay-peper** [zandero/rest.vertx#123]
When trying to run a project that uses rest.vertx with a java-17 jdk, we get the following exception:

```
java.lang.IllegalAccessError: class com.zandero.rest.data.ClassUtils (in unnamed module @0x1a0dcaa) cannot access class sun.reflect.generics.reflectiveObjects.TypeVariableImpl (in module java.base) because module java.base does not export sun.reflect.generics.reflectiveObjects to unnamed module @0x1a0dcaa

	at com.zandero.rest.data.ClassUtils.checkIfCompatibleType(ClassUtils.java:100)
...
```

It appears that the error is related to this line: https://github.com/zandero/rest.vertx/blob/8b7258e07a10f0319e28abdf4e5990cc3a1633bf/src/main/java/com/zandero/rest/data/ClassUtils.java#L100

**Comment by drejc** [comment]
`TypeVariableImpl` is part of the `sun.reflect.generics.reflectiveObjects` lib ... 
it might be that this was either moved or deprecated in java 17.

I must take a deeper look how to solve this issue ...

**Comment by jay-peper** [comment]
It seems we have to migrate away from this lib anyway, so no issue for us any more

**Comment by drejc** [comment]
FYI: Incompatibility with Java 17 (and earlier) are now with version 1.1 fixed
