### ISSUE TITLE
 rest.vertx is great, but i want to kone how to implement AsyncResult in restMethod

### ISSUE THREAD

**Issue by xiaomomo** [zandero/rest.vertx#14]
i want implement a async controller method like vertx.web 

here is my code

```
@GET
    @Path("/create")
    @Produces(MediaType.APPLICATION_JSON)
    @ResponseWriter(VertxResponseWriter.class)
    public Handler<Void> create(@Context RoutingContext context,
                                @Context HttpServerResponse response,
                                @Context Vertx vertx) {

        System.out.println(Thread.currentThread().getName() + "create start");
        context.request().getParam("id");
        SpaceDO spaceDO = new SpaceDO();
        Handler<Void> result = res -> {
            System.out.println("really return");
            response.setStatusCode(200)
                    .putHeader("content-type", "application/json")
                    .end("vapsce return");

        };
        spaceService.create(spaceDO, dbResult -> {
            System.out.println(Thread.currentThread().getName() + "async complete");
            result.handle(dbResult.result());
        });
        System.out.println(Thread.currentThread().getName() + "create method end");
        return result;
    }
```
but the com.zandero.rest.RestRouter#produceResponse method end end response mandatory,and system invoke error: `java.lang.IllegalStateException: Response has already been written`

```
if (!response.ended()) {
			response.end();
		}
```
why do this, and could i comment that statement in some fork?

**Comment by drejc** [comment]
This is currently not jet supported ... see issue #9 ... 
it's on the ToDo: list ...

**Comment by xiaomomo** [comment]
excited to hear,waiting implementation

**Comment by drejc** [comment]
Hm ... I took another look at your code ... and I'm not quite sure what you would like to achieve .... 
I have implemented this simple test:
```java
@GET
@Path("call")
@Produces(MediaType.APPLICATION_JSON)
@ResponseWriter(AsyncWriter.class)
public Dummy create() throws InterruptedException {

	System.out.println(Thread.currentThread().getName() + "create start");

	Handler<Dummy> output = res -> {
		res.value = res.value + "++";
		res.name = res.name + "++";
	};

	Dummy dummy = new Dummy("async", "called");
	spaceService.handle(dummy, handlerResult -> {
		System.out.println(Thread.currentThread().getName() + "complete");
		output.handle(handlerResult.result());
	});

	return dummy;
}
```

Where spaceService is:
```java
public class AsyncService {

	public void handle(Dummy dummy, Handler<AsyncResult<Dummy>> handler) throws InterruptedException {

		Thread.sleep(1000L);
		handler.handle(Future.succeededFuture(dummy));
		System.out.println(Thread.currentThread().getName() + " async service called ");
	}
}
```

and a AsyncWriter is:
```java
public class AsyncWriter implements HttpResponseWriter<Dummy> {

	@Override
	public void write(Dummy result, HttpServerRequest request, HttpServerResponse response) {
		System.out.println("produce result");
		response.setStatusCode(200)
		        .putHeader("content-type", "application/json")
		        .end("{\"name\": \"" + result.name + "\", \"value\": \"" + result.value + "\"}");
	}
}
```

In essence it does what you are intending to do ... or am I missing something?

**Comment by xiaomomo** [comment]
sorry reply message late , just received is message.  your code will response {"name": "async", "value": "called"};  but i want response  {"name": "async++", "value": "called++"}

**Comment by drejc** [comment]
Are you sure ... I have added a test RouteAsyncTest that works as expected .... have done a "real life" test though. Check out my test code and the TestAsyncRest implementation for that matter and keep me posted.

**Comment by xiaomomo** [comment]
sorry for my earlier describe bother you，i test your code in runtime, the code 
```
public class AsyncService {

	public void handle(Dummy dummy, Handler<AsyncResult<Dummy>> handler) throws InterruptedException {

		Thread.sleep(1000L);
		handler.handle(Future.succeededFuture(dummy));
		System.out.println(Thread.currentThread().getName() + " async service called ");
	}
}
```
is execute synchronous and return  `{"name": "async++", "value": "called++"}`

but i want `AsyncService` execute async like this

```
public class AsyncService {

    public void handle(Dummy dummy, Handler<AsyncResult<Dummy>> handler) throws InterruptedException {

        (new Thread(() -> {
            try {
                Thread.sleep(1000L);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            handler.handle(Future.succeededFuture(dummy));
        })).start();
        System.out.println(Thread.currentThread().getName() + " async service called ");
    }
}
```
in this time will return ` {"name": "async", "value": "called"}`

**Comment by drejc** [comment]
Ah .. now I understand your issue ... this is currently not possible to achieve.
As the REST method itself is a "blocking" method ... anything happening inside the REST method is currently not aware of the whole vertx event loop ... etc.

I'm thinking of some way to integrate this but have not yet come up with a nice solution ... 
the best way to do it, would be with some event bus annotations that would take care of situations like this.

**Comment by xiaomomo** [comment]
i just comment this code 

```
// finish if not finished by writer 
//		if (!response.ended()) {
//			response.end();
//		}
```

in the  com.zandero.rest.RestRouter#produceResponse, and the response could send asynchronously in the controller method

**Comment by drejc** [comment]
Sure ... I know that ... but this needs to be packaged well ... currently the logic is:

1. parse request / extract parameters 
1. execute method with parameters / inject if needed
1. use writer to produce response ... 

now in the second step we need the async stuff happening ...  and the 3rd step should take over the future result ... and there are different ways to do this ... 

One would be that the REST method itself returns a Handler<> ... than step 2. would know that this is some async stuff but step 3 would get only the result of the handler (not the handler itself) as this is only a output writer 

This is currently my thinking ... but need to do some more ... and some rewriting to do it an elegant way without breaking the old logic

**Comment by marcban** [comment]
Hello, as writer of issue #9, I also think that @xiaomomo solution would be very interesting, allowing asynchronous services with minimal changes to the existing API.

For example, if the `@Suspended` annotation is put on the HttpServerResponse argument , we could let the handler function write and end the response:

```
void asyncGet(@Suspended HttpServerResponse asyncResponse){ 
      doSomeThingAsynchronous(res->ctx.response().end(Json.encode(res.result());
}
```

It would be very close to standard JAX-RS :

`void asyncGet(@Suspended final AsyncResponse asyncResponse) {`

That would mean, for asynchronous services, only handle 1 and 2, which is already great. And the HttpServerResponse object already does what AsyncResponse does in JAX-RS.

**Comment by marcban** [comment]
May be in that case, we could just use a vert.x future, so there is no need to add a new specific class ?
```
@GET
	@Path("call")
	public Future<Dummy> create() {
		Future<Dummy> res = Future.future();
		doSomeThingAsynchronous(a->res.complete(res);
		return res;
}
```

Note : Currently, we use Enunciate for documenting the API, so our function returns "`Dummy`", but we can use the `@TypeHint` annotation for informing on the real return type

**Comment by drejc** [comment]
Sure will try to implement something with Future ... I think this will be a much simpler api than all other suggestions.

**Comment by drejc** [comment]
OK ... I have released a test version with Async execution ... should be up in about 30mins
```xml
<dependency>
  <groupId>com.zandero</groupId>
  <artifactId>rest.vertx</artifactId>
  <version>0.8.1-RC.1</version>
</dependency>
```
If a REST method returns a Future<Object> than a handler waits for the future to finish ... and returns the desired response.
The writer is determined according the future.result() type ... 

For instance: 
```java
@GET
@Path("async/{time}")
@ResponseWriter(GenericResponseWriter.class)
public Future<String> async(@Context Vertx vertx, @PathParam("time") int time) {
	Future<String> future = Future.future();
	slowService.async(vertx, future, time);
	return future;
}
```

Please give it a spin ...
