### ISSUE TITLE
Is this possible to print the cause of exception?

### ISSUE THREAD

**Issue by shuitai** [zandero/rest.vertx#146]
Because if fail to inject some class in restApi, it'll show exceptions like "Failed to getInstance class of type: .api.UserApi, with injector: injector.GuiceInjectionProvider!", but cannot know the root cause from the log.  So is it possible to print the cause of exception? The sample code is as follow. In RestRouter.java, line No. 101,

public static Router register(Router router, Object... restApi) {

        Assert.notNull(router, "Missing vertx router!");
        Assert.isTrue(restApi != null && restApi.length > 0, "Missing REST API class object!");
        assert restApi != null;

        for (Object api : restApi) {

            if (api == null) {
                continue;
            }

            // check if api is an instance of a class or a class type
            if (api instanceof Class) {

                Class<?> inspectApi = (Class<?>) api;

                try {
                    api = ClassFactory.newInstanceOf(inspectApi, getInjectionProvider(), null);
                } catch (ClassFactoryException | ContextException e) {
                    /////
                    System.out.println(e.getCause().toString);
                    /////
                    throw new IllegalArgumentException(e.getCause().toString);
                }
            }
}

**Comment by drejc** [comment]
An error should be logged by the ClassFactory that creates the class, ie. you should see a log entry. 
See: https://github.com/zandero/rest.vertx#logging. 
Alternatively use debugger and place your breakpoint inside the ClassFactory.newInstanceOf method, to see what is missing.

**Comment by shuitai** [comment]
@drejc 
I have checked that, even if the log level is debug, the detail cannot be shown. It is very important for us, because once the exception occurs and cannot register api, we could not find the root cause without the detail information for incorrect configurations in production env, not just debug or development.

**Comment by drejc** [comment]
If you take a deeper look at the api = ClassFactory.newInstanceOf you will see that the exception is logged and then returned  so you should get some additional data. 
The exception happens somewhere inside you injection provider implementation on this call: instance = provider.getInstance(clazz);

As you are the one who implements this part I suggest you put a try/catch inside your injection provider: 

```
 @Override
    public <T> T getInstance(Class<T> clazz) {
        try {
return injector.getInstance(clazz);
}
catch (Exception ex) {
  // LOG away
}
    }
```

Other than that you can always provide a custom patch if you want additional functionality to be included.

**Comment by shuitai** [comment]
This method you mentioned is not concise，I just want to be like springboot by using @AutoWired

This is sample code:

@Path("/api/")
public class TestApi {

  @Inject
  private TestService service

  @GET
  @Path("/{tenant}/{offering}")
  @Produces(MediaType.APPLICATION_JSON)
  public void apitest() {}
  }
}

If like the code, we cannot get real exception information or log if there are some injection errors.
You could try it, I just want to make the root cause more clear, it's just one line code work for you.

**Comment by drejc** [comment]
I honestly don't know what you are talking about. Please provide either a patch or test to demonstrate what you would like to achieve.
