### ISSUE TITLE
JAX-RS annotation inheritance

### ISSUE THREAD

**Issue by marcban** [zandero/rest.vertx#16]
As I use Enunciate for documentation, the web services classes are divided in interface and implementation. In that case, according to JAX-RS specs, I should'nt repeat the annotations on  implementation. But rest.vertx doesn't find the method in that case, as it use only `getAnnotation()` on the method without climbing to the superclass. I assume the same happens for parameter annotations.

see https://stackoverflow.com/questions/25916796/inheritance-with-jax-rs for the link to the spec, and https://stackoverflow.com/questions/10082619/how-do-java-method-annotations-work-in-conjunction-with-method-overriding/10082663 for an example of climbing to the superclass to read method annotations.

**Comment by drejc** [comment]
This is correct ... class / method / parameter inherited annotations are not taken into account.

**Comment by drejc** [comment]
Fix of issue is available on https://github.com/zandero/rest.vertx/tree/inherited_annotations branch.
