### ISSUE TITLE
RestBuilder::getRouter passes a List<Object> as an array element, instead of converting the list to an array of objects

### ISSUE THREAD

**Issue by juanavelez** [zandero/rest.vertx#18]
```
	private List<Object> apis = new ArrayList<>();
```

```
	private Router getRouter() {
		if (vertx == null) {
			return RestRouter.register(router, apis);
		}

		return RestRouter.register(vertx, apis);
	}
```

```
	public static Router register(Vertx vertx, Object... restApi) {

		Assert.notNull(vertx, "Missing vertx!");

		Router router = Router.router(vertx);
		return register(router, restApi);
	}
```

calling

```
        return new RestBuilder(vertx)
            .register(new MyObject())
            .errorHandler(WebApplicationExceptionHandler.class)
            .build();
```

```
@Path("/the")
@Slf4j
public class MyObject {
    @Path("/path")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public void login() {
```

From Intellij debugger

```
restApi:java.lang.Object[1] = {java.lang.Object[1]@5307}
->0: {java.util.ArrayList@5248} size = 1
-->0: {MyObject@2245}
```

which leads to an empty Map<RouteDefinition, Method> definitions in 

```
	public static Router register(Router router, Object... restApi) {

		// TODO: split into smaller chucks

		Assert.notNull(router, "Missing vertx router!");
		Assert.isTrue(restApi != null && restApi.length > 0, "Missing REST API class object!");
		assert restApi != null;

		for (Object api : restApi) {

			// check if api is an instance of a class or a class type
			if (api instanceof Class) {

				Class inspectApi = (Class) api;

				try {
					api = ClassFactory.newInstanceOf(inspectApi, injectionProvider, null);
				}
				catch (ClassFactoryException | ContextException e) {
					throw new IllegalArgumentException(e.getMessage());
				}
			}

			Map<RouteDefinition, Method> definitions = AnnotationProcessor.get(api.getClass());

			boolean bodyHandlerRegistered = false;
			boolean cookieHandlerRegistered = false;

			for (RouteDefinition definition : definitions.keySet()) {
```

because ```Object api``` here is not really ```MyObject``` but ```java.util.ArrayList``` which is not annotated

**Comment by drejc** [comment]
Not quite following what is the issue ... ?
You have registered MyObject.class as your API ... and It is not working? ...

**Comment by juanavelez** [comment]
From the README.md, it is apparent you can register an instance of an object

```
RestRest rest = new TestRest();
Router router = RestRouter.register(vertx, rest);

vertx.createHttpServer()
	.requestHandler(router::accept)
	.listen(PORT);
```

I am trying to do such but via the Builder API. The instance is saved in the RestBuilder's apis instance variable which is an actual ArrayList. The apis instance variable is fed to the RestRouter.register call, which accepts an array of Objects (VarArgs). By doing so, the first object of the VarArgs becomes the ArrayList and not the elements of such List.

**Comment by drejc** [comment]
Can you please provide the exact code ... I'm lost.

**Comment by juanavelez** [comment]
Sure, I will work on a reproducer of the issue.

**Comment by juanavelez** [comment]
More information. The RestBuilder.build() does build correctly, but the issue (and I am being picky here) is that the initial call by the build() method to getRouter() is not really doing anything because the passed parameter is an ArrayList. However down the build() code, there is an actual iteration of each of the elements of the apis variable which in that case is correctly registering the instance.
```
		// register APIs
		apis.forEach(api -> RestRouter.register(output, api));
```

 I still think that this method is incorrect an not necessary (well, getting a Vert.x Router is necessary)

```
	private Router getRouter() {
		if (vertx == null) {
			return RestRouter.register(router, apis);
		}

		return RestRouter.register(vertx, apis);
	}
```

**Comment by drejc** [comment]
I see ... the getRouter() method is needed ... because you can build up you RESTs in two ways ...
1. new RestBuilder(vertx). ... .build() OR
2. new RestBuilder(router) ... build() in case you want to add new routes to an existing router
so this is in place to match all possible cases ..

**Comment by juanavelez** [comment]
Correct, but the thing is that this call

```
return RestRouter.register(vertx, apis);
```

Does not register anything because the object passed (a List) is begin treated as a List itself which has no annotations so the iteration over

```
			Map<RouteDefinition, Method> definitions = AnnotationProcessor.get(api.getClass());
```

Returns an empty Map (because the class of api at that point is java.util.ArrayList which has no REST annotations and neither its methods)

I agree that the RestBuilder either by vertx or router is needed.

I believe the solution is

```
	private Router getRouter() {
               Object[] apiObjects = apis.toList(new Object[apis.size()])

		if (vertx == null) {
			return RestRouter.register(router, apiObjects);
		}

		return RestRouter.register(vertx, apiObjects);
	}
```

However, this would duplicate the "registration" because you still have

```
		// register APIs
		apis.forEach(api -> RestRouter.register(output, api));
```

so the correct solution would be

```
	private Router getRouter() {
            return vertx == null ? router : Router.router(vertx);
	}
```

**Comment by drejc** [comment]
O I see ... you want to register a list holding you APIs ... as:
```java
List<Object> list = new ArrayList();
list.add(api1);
list.add(api2);

new RestBuilder(vertx).register(list).build();
```
This will **not** work ... the list is taken as the API (which in this case it is not) ...

Usage is intended to be:
`new RestBuilder(vertx).register(api1, api2).build();`

**Comment by juanavelez** [comment]
Your RestBuilder api does provide a correct way to register things. The thing is that there is code that is not doing much besides creating the Vertx router. For example, try to debug

```
	@Test
	public void testCustomInput_WithBuilder(TestContext context) {

		Router router = new RestBuilder(vertx)
			                .register(TestReaderRest.class)
			                .build();
```

and you will see that the call to

```
return RestRouter.register(vertx, apis);
```

does nothing besides creating the vertx router because when iterates over the api loop variable, the class for the api object is a List which is not REST annotated, so there are no RouteDefinitions created.
