### ISSUE TITLE
Proposed enhancement: Provide a way to register exception handlers for specific exceptions

### ISSUE THREAD

**Issue by juanavelez** [zandero/rest.vertx#19]
The exception handling is very good but I think It'd be great if one could register ExceptionHandlers for specific exceptions. A proposal is to add a method to the ExceptionHandler interface that returns the list of exceptions it handles. If the list returned is null/empty, then it would handle any exception, otherwise the ExceptionHandler would handle the specific exception.

```
public interface ExceptionHandler<T extends Throwable> extends HttpResponseWriter<T> {
    default List<Throwable> getHandledExceptions() {
        return Collections.emptyList();
    }
}
```

For example, I need to raise a RuntimeException (BadRequestException) that I'd like the BadRequestExceptionHandler to handle. I can also raise another RuntimeException (UnauthorizedException) that I'd like the UnauthorizedExceptionHandler to handler. The BadRequestExceptionHandler would return a 400 HTTP status whereas UnauthorizedExceptionHandler would return a 401 HTTP status.

**Comment by drejc** [comment]
Sure ... but this functionality is actually already possible ... for instance ... if you annotate a method with @CatchWith you can list multiple exception handlers:

```java
@GET
@Produces(MediaType.APPLICATION_JSON)
@Path("multi/{bang}")
@CatchWith({IllegalArgumentExceptionHandler.class, WebApplicationExceptionHandler.class, MyExceptionHandler.class})
public String returnMultiBang(@PathParam("bang") String bang) throws ExecuteException {

		switch (bang) {
			case "one":
				throw new ExecuteException(405, "HTTP 405 Method Not Allowed");

			case "two":
			default:
				throw new IllegalArgumentException("Bang!");

			case "three":
				throw new NumberFormatException("WHAT!");

			case "four":
				throw new AbstractMethodError("ADIOS!");
		}
	}
```

where:

- public class IllegalArgumentExceptionHandler implements ExceptionHandler<IllegalArgumentException> {
- public class WebApplicationExceptionHandler implements ExceptionHandler<WebApplicationException> {
- public class MyExceptionHandler implements ExceptionHandler<Throwable> {

Exception handlers are used as listed ... first one matching the exception will be used.

Same logic applies globally when you register a global exception handler:
RestRouter.getExceptionHandlers().register(IllegalArgumentExceptionHandler.class, WebApplicationExceptionHandler.class, MyExceptionHandler.class); OR
RestBuilder...errorHandler(IllegalArgumentExceptionHandler.class, WebApplicationExceptionHandler.class, MyExceptionHandler.class) 

So in your case create two exception handlers ... for each specific exception ...

**Comment by juanavelez** [comment]
I see, the exception handler chosen is based on the Parameterized Type of the interface. So I need to create ExceptionHandlers whose type argument match the Exceptions I want to capture.

**Comment by drejc** [comment]
Exactly ... the first one matching will be used.
