### ISSUE TITLE
Add a way to set common logic in rest handlers

### ISSUE THREAD

**Issue by marcban** [zandero/rest.vertx#2]
In my application, web service are multi-tenant, so they all look the same

```java
@POST @Produces(MediaType.APPLICATION_JSON) @Consumes(MediaType.APPLICATION_JSON)
@Blocking @Path("/")
public ServiceResult dosomething(myClass param, @Context User user) {
	ServiceResult res = new ServiceResult();
	doAsTenant(user, () -> {
			... some logic here
	});
	return res;
}
```

``doAsTenant`` sets a thread local with the tenant id to protect access to resources.

Do you think it would be possible to add a common logic directly in the rest handlers, in order to keep only the business logic in the web service class ? For example, have a pre and post step for each service, set in RestRouter options ?

**Comment by drejc** [comment]
If I understand correctly you would like a pre/post filter every response goes through ... which alters the request / response ? In case the filter matches some criteria ... ? 

... the Pre filtering can be done via an additional vert.x handler where some custom context is set (pushed into vert.x @Context is set). See: https://github.com/zandero/rest.vertx#pushing-a-custom-context

For post filtering a custom ResponseWriter might be the solution ?

Not quite sure I understand your question ... maybe if you give me an example?

**Comment by marcban** [comment]
thank you for the quick answer.  As an example, here is the kind of "decoration" I would like to add to the rest handler

```java
Handler<RoutingContext> decorateHandler(Handler<RoutingContext> handler) {
  return (routingContext) -> {
     User user = calculateUserFromRequest(routingContext.request());
     addUserToThreadLocal(user);
     handler(routingContext);
    cleanUserThreadLocal();
}
```
This is a handler decorator, (it returns a handler from a handler).

The idea is to do like in popular framework (Spring Security for example), i.e add global data to thread local, before processing request, so that internal functions can access the user info for data protection.

**Comment by drejc** [comment]
I see ... hm ... 
the @Context (as per vert.x is thread local on it own) ... so anything pushed into the context via a handler is request based. So if you push this into the @Context than it will be visible only to the  handling request.

Under the hood RestRouter calls:
```java
context.put(createSomeUniqueKey, object);
```
where object in this case is your User object instance.

For instance ...

```java
Handler<RoutingContext> decorateHandler(Handler<RoutingContext> handler) {
  return (routingContext) -> {
     User user = calculateUserFromRequest(routingContext.request());

     RestRouter.pushContext(context, user);
}
```

You can push anything you fancy into the @Context ... its arbitrary ... 
then you can utilize the user in the REST end point

```java
@POST 
@Blocking @Path("/")
public ServiceResult dosomething(myClass param, @Context User user) {
	ServiceResult res = new ServiceResult();
	doAsTenant(user, () -> {
			... some logic here
	});
	return res;
}
```

Threads are cleaned up after each request ... so @Context is only visible to them.

**Comment by marcban** [comment]
I see, in that case il would allow me to use my own ``User`` class instead of the vertx auth user.
...but if still have to repeat the ``doAsTenant`` on every method, which I wanted to avoid.

I tried to add a handler before the rest one, to put the user in thread local, but it does'nt work, as my service are blocking, and blocking handlers are in a different thread.

Anyway, I understand this is maybe "over optimization", and too specific...

**Comment by drejc** [comment]
Yes this is the idea behind vert.x ... RestRouter utilizes vert.x as far as possible ... 

Will think about an option to use a custom annotation to push the context / skip manual Context handlers ... so everything is one place ... (would also come handy if different context handlers are needed for different RESTs).

Will close this issue for now.

**Comment by marcban** [comment]
...One way of doing it without adding  new global functios/optionsn could be to have a `RestRouterBuilder` class, with a "fluent" api, instead of static functions on RestRouter.

in that case, it would be easier to add options to the router: 

```java
new RestRouterBuilder() // instantiate a new builder
 .errorHandler(myErrorHandler) //register my error handler
 .handlerDecorator(myHandlerDecorator) // register my decorator
 .register(router, myWebService) // register my web services
 .register(router, myWebOtherService);
```

For compatibilty , RestRouter static functions would use a static RestRouterBuilder member.

**Comment by drejc** [comment]
Great idea ... will add this to feature list ... :) see here:https://github.com/zandero/rest.vertx/projects/1

**Comment by marcban** [comment]
thanks again!

**Comment by marcban** [comment]
(after thinking on the API last night)
a more "fluent" RestRouterBuilder API would be

```java
new RestRouterBuilder() // instantiate a new builder
 .errorHandler(myErrorHandler) //register my error handler
 .handlerDecorator(myHandlerDecorator) // register my decorator
 .register( myWebService) // register my web services
 .register(myWebOtherService) // register another web service
  .buildRoutes(router); // build routes
```

not a big deal anyway..

**Comment by drejc** [comment]
Will be included in some form on the next release.
Today I have pushed a new release with improved type safety and revamped exception handling.  The exception handling API has slightly changed and simplified.

**Comment by marcban** [comment]
I tested the new Exception API, simpler and very clean indeed !

**Comment by drejc** [comment]
Thanks ...
