### ISSUE TITLE
Not able to register Custom Filter Class in Vertx RestRouter

### ISSUE THREAD

**Issue by HR2132** [zandero/rest.vertx#21]
I have created custom Authentication Filter:
**public class AuthenticationFilter implements javax.ws.rs.container.ContainerRequestFilter**

As this filter should invoked for each rest API call, I am trying to register it in router using:
**RestRouter.register(vertx, AuthenticationFilter.class)**

but this filter is not invoked.

in case of other J2EE Container it is working fine as it uses:
register of ResourceConfig . 

Please suggest any Solution or alternative for this Issue.

**Comment by drejc** [comment]
ContainerRequestFilter is currently not supported (as vert.x does things a little bit different)

Depending on what you want to achieve there are several ways to do authentication with vert.x
But it all boils down to implementing a handler that either fills in the local Context or throws an exception ... 

See: [User roles and authorization](https://github.com/zandero/rest.vertx#user-roles--authorization)
for inspiration.
