### ISSUE TITLE
When using Proxies, RouteDefinitions are not created correctly

### ISSUE THREAD

**Issue by juanavelez** [zandero/rest.vertx#23]
I am working on adding Spring Validation to the REST Controllers so I have created an interface

```
@Path("/user")
public interface LoginControllerContract {
    @Path("/login")
    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    Future<UserInfo> login(@Valid Credentials credentials);
}
```

And an implementation class

```
@Component
@Slf4j
@Validated
public class LoginController implements LoginControllerContract {
    private final JDBCClient jdbcClient;

    @Autowired
    public LoginController(JDBCClient jdbcClient) {
        this.jdbcClient = jdbcClient;
    }

    @Override
    public Future<UserInfo> login(@Valid Credentials credentials) {
```

In my bootstrap verticle where I declare an @Autowired to LoginControllerContract, I register the Controller with rest.vertx

```
    @Autowired
    private LoginControllerContract loginController;
```

```
    /**
     * Sets up the router with the login controller
     * @param router the vertx web router to set up
     */
    private void setupLoginController(Router router) {
        new RestBuilder(router)
            .register(loginController)
            .errorHandler(HttpStatusExceptionHandler.class)
            .build();
    }
```

When I disable the validation AOP, I get an actual object to LoginController and the registration works fine and I can reach the endpoint /user/login. However when I enable the validation AOP, Spring proxies the LoginController class which makes the registration not do anything and I get a "Resource Not Found" error. I tried following the code but it seems the method AnnotationProcessor::isRestCompatible is not correctly identifying the methods which are rest compatible. 

```
	/**
	 * @param method to check if REST compatible
	 * @return true if REST method, false otherwise
	 */
	private static boolean isRestCompatible(Method method) {

		return (!method.getDeclaringClass().isInstance(Object.class) &&
		        !isNative(method) && !isFinal(method) &&
		        (isPublic(method) || isInterface(method) || isAbstract(method)));
	}
```

Within the proxy is choosing all the methods which makes the RouteDefinition itself to not be built correctly.

**Comment by juanavelez** [comment]
Reproducer https://github.com/juanavelez/rest-vertx-issue-23

**Comment by drejc** [comment]
So you need to provide an implementation of a InjectionProvider class,
this class is then used to get the needed class instances on the fly.

In your case this is the Proxy class that does this.

```java
 public static class ProxyProvider implements InjectionProvider {

        LoginControllerContract loginController = new LoginController();

        @Override
        public <T> T getInstance(Class<T> clazz) {

            return (T) Proxy.newProxyInstance(clazz.getClassLoader(),
                                              new Class[] { LoginControllerContract.class },
                                              (p, m, a) -> m.invoke(loginController, a));
        }
    }
```

```java
  new RestBuilder(router)
            .injectWith(ProxyProvider.class)
            .register(LoginController.class)
            .build();
```

**Comment by juanavelez** [comment]
Thank you for reply. Unfortunately this does not work as the proxy is not being used. The registration process creates a new instance of the ```LoginController.class``` (```register(LoginController.class)```) and registers that as the handler. The proxy needs to be called. You can test this by changing the proxy to print something before it invokes the actual method:

```
        LoginControllerContract proxy = (LoginControllerContract) Proxy.newProxyInstance(this.getClass().getClassLoader(),
            new Class[] { LoginControllerContract.class },
            (p, m, a) -> {
                System.out.println("hello");
                return m.invoke(loginController, a);
            }
        );
```

You will see that the proxy is not used

**Comment by drejc** [comment]
OK my bad ... thought it was a simple factory issue ... will dive deeper
...

**Comment by juanavelez** [comment]
Thank you for reopening the issue and taking a deeper dive. Also, I forgot to add that in the real situation I would not know the actual implementation class only the interface. Unfortunately calling RestBuilder::register with an argument of LoginControllerContract.class fails as the code tries to find a default constructor which interfaces don't have. Nevertheless, the interface(s) and its methods would be properly annotated with the appropriate REST annotations.

I wonder if the issue is associated to the fact that AnnotationProcessor::isRestCompatible not really checking for REST-based annotations like it was before.

**Comment by drejc** [comment]
Must take a look.  However interface annotations are supported, so those
should work.
Will try to find a general solution.

**Comment by drejc** [comment]
You were right it was the _isRestCompatible_ method preventing the correct binding.  
Explicitly the !isFinal(method) check. 

I have added this check to prevent binding final Object methods like equals(), toString() ... and to speed things up when searching for compatible methods. 
In this case it prevents the binding of the correct method.

Will provide a fix in the next day or two ... 
in the meanwhile if you need a working copy just clone the repo and build a local version with this implementation of _isRestCompatible_

```java
/**
	 * @param method to check if REST compatible
	 * @return true if REST method, false otherwise
	 */
	private static boolean isRestCompatible(Method method) {

		return (!method.getDeclaringClass().isInstance(Object.class) &&
		        !isNative(method) && 
		        (isPublic(method) || isInterface(method) || isAbstract(method)));
	}
```

**Comment by juanavelez** [comment]
Indeed, your suggested change worked like a charm. Thank you!
