### ISSUE TITLE
Given exception handler not used

### ISSUE THREAD

**Issue by jsirach** [zandero/rest.vertx#29]
If i'm overlooking something, please correct me.

Currently i'm building a router with

`
        for (Collection api : Collection.values()) {
            apiList.add(api.getResource());
        }
        return new RestBuilder(vertx)
                .register(apiList.toArray())
                .errorHandler(RestFallbackExceptionHandler.class)
                .build();`

Which correctly builds the router.

I have created an error handler with:

`
@Produces("application/json")
public class RestFallbackExceptionHandler implements ExceptionHandler<DefaultRestException> {

    /**
     * Logger for the handler.
     */
    Logger LOG = LogManager.getLogger(RestFallbackExceptionHandler.class);

    /**
     * Writes the error to the output.
     *
     * @param exception The exception to get the data from.
     * @param request The http request made.
     * @param response The response to be send back to the user.
     */
    @Override
    public void write(DefaultRestException exception, HttpServerRequest request, HttpServerResponse response) {
        response.setStatusCode(exception.getStatus());
        try {
            response.end(Serialization.getDefaultObjectMapper().writeValueAsString(exception));
        } catch (JsonProcessingException ex) {
            LOG.error("Could not serialize default REST error exception");
            response.end(exception.getMessage());
        }
    }
}
`

Following the example on the github page.

When i access a REST endpoint for which the user is unauthorized i'm getting the following result:

"HTTP 401 Unauthorized"

With in my log file:
"Resolving to generic exception handler: com.zandero.rest.exception.GenericExceptionHandler"

I was expecting my exception handler "RestFallbackExceptionHandler" to be used.

The Serialization.getDefaultObjectMapper() is a jackson objectmapper

**Comment by drejc** [comment]
You need to specify the exception type you want to catch.

In your case I assume you want to catch **DefaultRestException**, so you need to tell rest.vertx the exception type: 
```java
@Produces("application/json")
public class RestFallbackExceptionHandler implements ExceptionHandler<DefaultRestException> {
```
Otherwise rest.vertx can't match the thrown exception to the exception handler and defaults to the GenericExceptionHander instead.

Hope this helps.

**Comment by jsirach** [comment]
I did a copy paste error i think, i have put the DefaultRestException there.

I'm trying to assign it as a global exception handler. I think i'm misinterpreting your documentation. Which class generic should i use to have it globally assigned?

(currently at work so unable to try out now ;) )

**Comment by drejc** [comment]
I have this in my own code ... 
```java
@Produces("application/json;charset=UTF-8")
public class RestErrorHandler implements ExceptionHandler<Throwable> {

	private static final Logger log = LoggerFactory.getLogger(RestErrorHandler.class);

	@Override
	public void write(Throwable result, HttpServerRequest request, HttpServerResponse response) {

		log.error("Request failed: ", result);

		response.setStatusCode(400);

		String message = result.getMessage();
		if (StringUtils.isNullOrEmptyTrimmed(message)) {
			message = result.toString();
		}

		response.end(JsonUtils.toJson(new ErrorDto(400, message)));
	}
}```

and in the Router:
```java
Router router = new RestBuilder(vertx)
.... some APIs ... 
			                .errorHandler(RestErrorHandler.class)
			                .build();
```

This will catch any exception thrown (i.e. Throwable) ... not only specific ones ...

**Comment by jsirach** [comment]
Works like a charm, thanks!

Closing the issue.

**Comment by drejc** [comment]
Cool ...
