### ISSUE TITLE
Allow methods without @Path annotation (JAX-RS compatibilty) 

### ISSUE THREAD

**Issue by marcban** [zandero/rest.vertx#3]
in JAX-RS, methods annotated with ``@GET``, ``@POST``, ``@PUT``, or ``@DELETE`` don't need a ``@PATH`` annotation if class already has one (they will get the path from the class).

For the moment, such methods are not added to the router by ``RestRoute.register``, you need to add a ``@Path("/")``.

**Comment by drejc** [comment]
This is correct @Path is used to find the REST methods ... should probably also consider if there is only GET, POST .. present. 
Nice catch ... will fix in the next release.

**Comment by drejc** [comment]
https://github.com/zandero/rest.vertx/commit/eb1ed2324f33d61a6967ae35a72a51a3a658f493
https://github.com/zandero/rest.vertx/commit/3894bc0b7f116303b5346c236a5648733f08be58
