### ISSUE TITLE
Detection of regex in path is too sensible

### ISSUE THREAD

**Issue by cyr62110** [zandero/rest.vertx#32]
Hi,

We are using in our application versioned path like the following:
```java
@Path("/api/admin/1.0/categories")
```

Unfortunately, the ValidatingUtils.isRegEx is picking 1.0 as a valid regex and is creating a path param named "param0" for it. Therefore we need to add a parameter @PathParam("param0") in all of our methods otherwise we get this error:
```
Invalid parameter type for: @PathParam("param0") for: /api/admin/1.0/categories
```

We have found multiple ways to overcome the issue but it could be good if in the future we can enable/disable which type of detection we want for path params.

Best,

**Comment by drejc** [comment]
You are correct ... the RegEx detection and use of RegEx expression in paths is somewhat broken.
There is already an open bug #25 that will address this issue.

Will try to find a better way of dealing with RegEx expressions ... if you have any suggestions for a regEx path syntax feel free to post it here.

**Comment by drejc** [comment]
Issue is fixed (not released yet)

VertX regEx must now have following format: `:parameter:regEx` or `{parameter:regEx}`
all other are considered simple paths.

Could you give it a spin, and give me same feedback if this solved your issues.

**Comment by cyr62110** [comment]
Thanks. I have tried and I can now use 1.0 in the path without issue.
