### ISSUE TITLE
QueryParam should be URLDecoded

### ISSUE THREAD

**Issue by tsu1137** [zandero/rest.vertx#33]
Hi 
I'm trying out rest.vertx (latest version, 0.8.6), so far I like it very much. There's just a small issue related to service methods with QueryParam.

Observation:
Service methods which use @QueryParam receive the URL *encoded* param, for example "Hello%20World" 

Expected:
Standard behaviour would be to get the URL *decoded* query param, i.e. "Hello World"

Cheers
Thomas

**Comment by drejc** [comment]
I'm aware of this bug, and it is already fixed, but not released (if you wish you can take the latest code and build it yourself)

I'm in the process of fixing the RegEx query problems and this fix will be a part of the next release.

**Comment by tsu1137** [comment]
Thanks Andrej that's very cool news. I'll try it out.
Cheers
Thomas

**Comment by drejc** [comment]
WIll be released very soon with 0.8.7 version
