### ISSUE TITLE
Routes checking @RolesAllowed have order 0

### ISSUE THREAD

**Issue by cyr62110** [zandero/rest.vertx#35]
Hi,

I was having the following exception on my POST endpoints with a @RoleAllowed annotation:
```
java.lang.IllegalStateException: Request has already been read
	at io.vertx.core.http.impl.HttpServerRequestImpl.checkEnded(HttpServerRequestImpl.java:438)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handler(HttpServerRequestImpl.java:203)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.handler(HttpServerRequestWrapper.java:39)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:73)
```

After investigation I found that all route checking the roles are registered with the order 0 because of the following line:
https://github.com/zandero/rest.vertx/blob/8925ffd5e2c7d337deb01e9a15fb47d7a93601d0/src/main/java/com/zandero/rest/RestRouter.java#L424

However for the route serving the content there is a check avoiding this case:
https://github.com/zandero/rest.vertx/blob/8925ffd5e2c7d337deb01e9a15fb47d7a93601d0/src/main/java/com/zandero/rest/RestRouter.java#L170-L172

I found a workarround by adding the following lines before calling RestRouter.register which make sure that parsing the body is done before anything else:
```java
router.route().order(Integer.MIN_VALUE)
                .handler(BodyHandler.create())
```

Best,

**Comment by drejc** [comment]
Will take a look ... it seems like in this particular combination the body handler is added a little bit to late.
