### ISSUE TITLE
Exception when validating a method taking no parameter.

### ISSUE THREAD

**Issue by cyr62110** [zandero/rest.vertx#36]
Hi again,

After I registered a Validator I started to get the following exception when the RestRouter tries to validate a function that takes no parameter. The validator library that I am using is hibernate-validators 6.0.13.

The exception I get is the following:
```
java.lang.IllegalArgumentException: HV000116: The method parameter array cannot not be null.
	at org.hibernate.validator.internal.util.Contracts.assertNotNull(Contracts.java:45) ~[hibernate-validator-6.0.13.Final.jar:6.0.13.Final]
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateParameters(ValidatorImpl.java:222) ~[hibernate-validator-6.0.13.Final.jar:6.0.13.Final]
	at com.zandero.rest.RestRouter.validate(RestRouter.java:533) [rest.vertx-0.8.7.jar:?]
```

And below you will find the signature of one of the method that cause the problem:
```kotlin
@GET
@RolesAllowed(Scope.CATEGORIES_LIST_PUBLIC)
fun listCategories(): Future<List<CategoryUserResource>>
```

A simple fix may be to check if there is at least one parameters before trying to call validateParameters.

Best,

**Comment by drejc** [comment]
Hm ... not quite sure it is a rest.vertx issue ... can you provide the assigned validator you use.

**Comment by cyr62110** [comment]
Yes, I uses [hibernate-validator 6.0.13](https://mvnrepository.com/artifact/org.hibernate.validator/hibernate-validator/6.0.13.Final).

To create my validator, I do:
```kotlin
val validatorFactory = Validation.buildDefaultValidatorFactory()
val validator = validatorFactory.validator
```

Then I assign it to the RestBuilder:
```kotlin
val builder = RestBuilder(router)
                .validateWith(validator)
```

Best,

**Comment by drejc** [comment]
Will take a look.
