### ISSUE TITLE
Verticle mutil instance, bug ExceptionHandlerFactory has shared handlers

### ISSUE THREAD

**Issue by pipinet** [zandero/rest.vertx#38]
Verticle mutil instance, bug ExceptionHandlerFactory has shared handlers...
when checkIfAlreadyRegistered will throw Exception

**Comment by drejc** [comment]
Please include a test case that replicates this issue, thanks

**Comment by drejc** [comment]
Is this still an issue, I could not replicate this locally on my machine (as far as possible from the description). If it is please provide use case to replicate, otherwise I will close it.
