### ISSUE TITLE
Allows to use @QueryParam with classes that have a String constructor (JAX-RS compatibility)

### ISSUE THREAD

**Issue by marcban** [zandero/rest.vertx#4]
according to JAX-RS doc, the type of a query parameter can:

- Be a primitive type
- Have a constructor that accepts a single String argument
- Have a static method named valueOf or fromString that accepts a single String argument (see, for example, Integer.valueOf(String))
- Have a registered implementation of ParamConverterProvider JAX-RS extension SPI that returns a ParamConverter instance capable of a "from string" conversion for the type.
- Be List<T>, Set<T> or SortedSet<T>, where T satisfies 2, 3 or 4 above. The resulting collection is read-only.

ok, that's a lot to implement... maybe the 2 first one would be nice :-)

Note : I tried to use a RequestReader, but it does'nt seem to work with QueryParam. For the moment I'll stick with string parameters

**Comment by marcban** [comment]
Note : I tried with the classical timestamp example
http://www.developerscrappad.com/2308/java/java-ee/rest-jax-rs/java-rest-jax-rs-2-0-how-to-handle-date-time-and-timestamp-data-types/

**Comment by drejc** [comment]
RequestReader is intended for POST, PUT body request reading not for query parameters.
However basic primitive type Query parameters should work (int, boolean, String ...).

The other points on the list will be included on the ToDo

**Comment by drejc** [comment]
rest.vertx tries to initialize a class:
* converting String to primitive type if class is a String or primitive type
* using a single String constructor
* using a single primitive type constructor if given String can be converted to the specific type  
* using static method _fromString(String value)_ or _valueOf(String value)_ 

It **does not**:
* initialize with a registered implementation of ParamConverterProvider 
* or create a List, Set or SortedSet, where T satisfies 2, 3 or 4 above
