### ISSUE TITLE
Please add support of @BeanParam

### ISSUE THREAD

**Issue by mxmind** [zandero/rest.vertx#40]
Hi, that will be very handy to be able to use simple POJO as the parameter's aggregator. Please, see the following Javadoc https://docs.oracle.com/javaee/7/api/javax/ws/rs/BeanParam.html

**Comment by drejc** [comment]
I'm quite busy at the moment ... will see if I can squeeze this one in

**Comment by drejc** [comment]
Basic @BeanParam support added, to be released in version 0.9.0
