### ISSUE TITLE
Support Multiple HTTP Methods/Verbs for Same Route

### ISSUE THREAD

**Issue by YounesRahimi** [zandero/rest.vertx#46]
Currently one can set only one HTTP method for a route. While in other frameworks like Spring Web you can set multiple HTTP methods for the same route. Being able to set multiple HTTP methods lets the developer migrate a route's HTTP method over time from one to another or simply to respond to the same requests with different HTTP methods. 

Example code:
```java
@Path("/test")
public class TestResource{

    @GET
    @POST
    public String getName(){
        return "Hello Java";
    }
}
```

**Comment by drejc** [comment]
Not sure if this is a good practice, I'm quite reluctant to introduce this.

**Comment by drejc** [comment]
This would require a significant rewrite, plus mixing endpoints in not a good practice.
Closing for now ...
