### ISSUE TITLE
DELETE body with empty body not working

### ISSUE THREAD

**Issue by drejc** [zandero/rest.vertx#47]
Good evening,

I've seen the issue has been closed, but i'm seeing some odd behavior.

Using vertx web 3.8.0, updated rest.vertx to 0.8.9.

I'm having one path with a GET and a DELETE
1:
    @GET
    @Path("tokens/:tokenReferenceId")
2:
    @DELETE
    @Path("tokens/:tokenReferenceId")

I'm noticing after the update the DELETE annotated method is results in a 404. But after adding an empty body to my delete request, the DELETE annotated method is found again.

It looks like DELETE now requires a body to be able to be identified.

For now for me it's not a problem because my calls are made generic in my front-end, so adding an empty object is not that big of a deal. But it was unexpected.

You want me to open a new report?

_Originally posted by @jsirach in https://github.com/zandero/rest.vertx/issues/42#issuecomment-525064889_

**Comment by drejc** [comment]
@jsriach ... was trying to replicate the described issue, but was unable to.

I have created the following routes:
```java
	@Delete("/it/:tokenReferenceId")
	@RequestReader(DummyBodyReader.class)
	@ResponseWriter(TestDummyWriter.class)
	public Dummy deleteWithBody(@PathParam("tokenReferenceId") String tokenReferenceId, Dummy postParam) {

		postParam.name = "Received-" + postParam.name;
		postParam.value = "Received-" + postParam.value;

		return postParam;
	}

	@Delete("/empty/:tokenReferenceId")
	public String deleteWithoutBody(@PathParam("tokenReferenceId") String tokenReferenceId) {
		return "success";
	}
```

Both work as expected in my unit test, can you create a short code snipped that replicates this issue on your side.

**Comment by jsirach** [comment]
Sorry for the late response. Will come back to you asap!

**Comment by jsirach** [comment]
Removing @Consumes("application/json") from class level and only on methods which should consume solved the issue. 🤦‍♂️

You can close the issue, sorry for taking your time!
