### ISSUE TITLE
@Context only injects values on method level, not on class level

### ISSUE THREAD

**Issue by dankristensen** [zandero/rest.vertx#5]
Hi

When i try to inject a Context like below, this is not made available. It works fine on method level

public class SomeRest {
@Context Vertx vertx;
}

**Comment by drejc** [comment]
Yes ... @Context is currently only injected as a REST method argument not as a class variable.
@Context is a thread local state of the current request (thread safe), I don't think it is a good idea to mix a class variable (global state) with the local request/method (execution state). 

If you need you can access vertx instance use the classic: `Vertx.vertx()`

**Comment by dankristensen** [comment]
The reason i ask, is that i am working on changing an existing JAX-RS jersey solution to vert.x. And the existing solution is allowing this. I will change to use the @Context on the method instead.

**Comment by drejc** [comment]
Yes I'm aware that some frameworks support this kind of injection ... and for the Vertx.vertx() instance it would be a legit inject (as this is a global variable) ... but @Context is a request specific thing and it would somehow break the "logic" ... will think of a way to provide global state variables to the class. 
In the funnel is also an integration with existing injection frameworks (like Guice) so stay tuned.

**Comment by marcban** [comment]
On my project, I implemented injection using the spring verticle factory example, it works like a charm with rest.vertx. You can inject for example the vertx object, the config, other verticles...

https://github.com/vert-x3/vertx-examples/tree/master/spring-examples/spring-verticle-factory

**Comment by drejc** [comment]
@marcban will take a look ... thanks for the info
