### ISSUE TITLE
Does this support OpenAPI or Swagger?

### ISSUE THREAD

**Issue by MohiuddinM** [zandero/rest.vertx#51]

**Comment by drejc** [comment]
Currently (to my knowledge) there is no swagger or openAPI generator available, to generate fully rest.vertx compatible code.

You could try using one that converts to a rest.easy output, and then provide some additional code to bind the generated API / have not tried it my self.

rest.vertx however provides a lot of additional functionality (like writers / reader and error handlers) that are binded directly with annotations on the API. I'm not sure that this can be expressed with the current swagger definition (but correct me if I'm wrong).

So if you need swagger to API conversion for the server side for rest.vertx you will probably need to define your own templates for the openAPI generator.
