### ISSUE TITLE
Add support to @ApplicationPath

### ISSUE THREAD

**Issue by mrmx** [zandero/rest.vertx#52]
Would be great to have a base class with eg: @ApplicationPath("v1") so any subclasses will be routed relative to the base class path, eg: /v1/resource1 etc..

**Comment by drejc** [comment]
Not quite sure what you have in mind, ... could you provide a code example how this would look like?

**Comment by mrmx** [comment]
E.g:

`
@ApplicationPath("/v1")
@Produces("application/json")
public abstract class AbstractRestEndpointV1 {
}

//Then a child class:
@Path("/child")
public class ChildEndpoint extends AbstractRestEndpointV1 {
}
`

The ChildEndpoint class sample will inherit a common ApplicationPath and default Produces and will have an absolute path of /v1/child.
The benefits are clear inheritance ones (eg: easy to have new V2 api paths).

Hope you get the picture. Also @ApplicationPath is part of the JAX-RS specs :-)

**Comment by drejc** [comment]
Will take a look, should not be a problem implementing
