### ISSUE TITLE
How could I upload file use rest.vertx?

### ISSUE THREAD

**Issue by shuitai** [zandero/rest.vertx#53]

**Comment by shuitai** [comment]
How could I upload file with rest.vertx?

**Comment by drejc** [comment]
For the top of my head ... best way would be to bind a POST request and then use the @Context RoutingContext to get file uploads ... 

Something like this: 

@POST("upload")
public String fileUpload(@Context RoutingContext context) {
        Set<FileUpload> fileUploadSet = routingContext.fileUploads();
        Iterator<FileUpload> fileUploadIterator = fileUploadSet.iterator();
        while (fileUploadIterator.hasNext()){
          FileUpload fileUpload = fileUploadIterator.next();

          // To get the uploaded file do
          Buffer uploadedFile = vertx.fileSystem().readFileBlocking(fileUpload.uploadedFileName());
...
}

probably you will need to set the correct content type ...

**Comment by shuitai** [comment]
Ok, thanks, It is helpful.
