### ISSUE TITLE
Could @Get support request body?

### ISSUE THREAD

**Issue by shuitai** [zandero/rest.vertx#59]
@GET
    @Path("/list")
    @Consumes("application/json")
    @Produces("application/json")
    @RolesAllowed("system:user:list")
    public TableDataInfo list(SysUser user, @Context HttpServerRequest request) {
        ....
    }

**Comment by drejc** [comment]
By default **rest.verx** ignores body in GET requests ... 
but I see that is technically as per specs allowed ... 
This is however highly unusual and not wildly used by servers and clients.

https://stackoverflow.com/questions/5216567/is-this-statement-correct-http-get-method-always-has-no-message-body

> So, in my opinion this means that you can add a message body to a GET request, (and this should answer your original question), but you have to be careful. The case mentioned in the specs is not the only one you have to be aware, many tools, client and servers are simply not expecting a message body and may misbehave. For example in Chrome, XMLHttpRequest will drop the message body for GETs.

**Comment by drejc** [comment]
You can try and alter requestHasBody() method in RouteDefinition class and add GET ... 

 ```
public boolean requestHasBody() {

        // https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/
        // also see:
        // https://www.owasp.org/index.php/Test_HTTP_Methods_(OTG-CONFIG-006)
        return HttpMethod.DELETE.equals(method) ||
                   HttpMethod.POST.equals(method) ||
                   HttpMethod.PUT.equals(method) ||
                   HttpMethod.PATCH.equals(method) ||
                   HttpMethod.TRACE.equals(method);
    }
```
