### ISSUE TITLE
Not possible to have multiple mediatype's in @Produces for a method

### ISSUE THREAD

**Issue by dankristensen** [zandero/rest.vertx#7]
When a method is annotated with

    @Produces({ MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON })

And the request is sent with the "Accept: application/xml", the response is returned as JSON.

If it is called with "Accept: application/json", the response works ok and returns json.

It looks like this code is the main problem:

				for (MediaType produces : definition.getProduces()) {
					response.putHeader(HttpHeaders.CONTENT_TYPE, produces.toString());
				}

By default ALL elements in Produces are added. This means the last will always win. Instead it should look at what is in Accept header on the request.

**Comment by drejc** [comment]
Will look into it ... probably a bug

**Comment by drejc** [comment]
Fixed in version 0.7.2
