### ISSUE TITLE
Add suspendable function support to asynchronous response types 

### ISSUE THREAD

**Issue by nhmarsh** [zandero/rest.vertx#78]
Currently, the code at [RouteDefinition](https://github.com/zandero/rest.vertx/blob/master/src/main/java/com/zandero/rest/data/RouteDefinition.java#L733) attempts to identify if a function is `suspendable` - however, when invoking that method, it fails to provide the correct `CoroutineContext` to the function being invoked. While this code is not written in `Kotlin` and therefore will likely lack full support, a hook should be added to supply the correct coroutine context to the method.

Here a controller definition that will reproduce this issue:

```
    @GET
    @Path("/responsetestasync")
    @Produces(MediaType.APPLICATION_JSON)
    @PermitAll
    suspend fun testAsync(): Response {
        delay(500)
        return Response.accepted(JsonObject().put("testkey", "testval")).build()
    }
```

This will throw a NPE [here](https://github.com/zandero/rest.vertx/blob/master/src/main/java/com/zandero/rest/RestRouter.java#L519), because there is currently not a hook to supply the current `coroutineContext` injected by Kotlin to a suspendable function.

**Comment by drejc** [comment]
Have you tried https://github.com/YounesRahimi/rest.vertx-kotlin-coroutines ?
The suspend part was written by @YounesRahimi as far as I remember I have only merged his solution.
Maybe @YounesRahimi can take a look how to improve this.

**Comment by nhmarsh** [comment]
I have not seen that. I'll have a look and see if that fixes the issue.

**Comment by drejc** [comment]
@nhmarsh is this still an open issue? I have not had the time to check this with Kotlin.
