### ISSUE TITLE
HttpMethod problem in vertx4

### ISSUE THREAD

**Issue by nuty456** [zandero/rest.vertx#87]
Hello, there is difference in vertx4, whole new different io.vertx.core.http.HttpMethod in vertx core.

**Comment by drejc** [comment]
**rest.vertx** is not jet compatible with **vertx4**, as **vertx4** deprecates some things and brings other changes.
As far as I'm aware there is not a final **vertx4** release, once it will be published I will migrate / release a rest.vertx version for **vertx4**. Until then use the latest **vertx3** version.
