### ISSUE TITLE
The detailed exception is hidden when fail to getInstance 

### ISSUE THREAD

**Issue by shuitai** [zandero/rest.vertx#88]
try {
                instance = provider.getInstance(clazz);
                if (instance == null) {
                    throw new ClassFactoryException("Failed to getInstance class of type: " + clazz.getName() + ", with injector: " +
                            provider.getClass().getName() + "!", null);
                }
            } catch (Throwable e) {
                throw new ClassFactoryException("Failed to getInstance class of type: " + clazz.getName() + ", with injector: " +
                        provider.getClass().getName() + "!", e);
            }

please print out the detail exceptions for debugging better.

**Comment by drejc** [comment]
Please provide a little more info, about what you are seeing right now and what your desired output would look like.

**Comment by drejc** [comment]
Don't know what the "details" should be ... closing issue.
