### ISSUE TITLE
Allow  asynchronous web services

### ISSUE THREAD

**Issue by marcban** [zandero/rest.vertx#9]
For the moment, all the services I wrote had the "Blocking" annotation.

It works pretty well, but its is not an ideal solution for an asynchronous framework like vertx.

It would be interesting to have a way of writing asynchronous methods, either with the Jax-RS 2.0 [AsyncResponse](https://docs.oracle.com/javaee/7/api/javax/ws/rs/container/AsyncResponse.html) (which is quite complex) or by letting the methods have a way of calling a "resume" method with the result as a parameter.

**Comment by drejc** [comment]
I think this could be achieved using the Vert.X message bus system ... which I already plan to make easier to use with annotations ... combining those two you could achieve this.

**Comment by drejc** [comment]
OK ... I have released a test version with Async execution ... should be up in about 30mins
```xml
<dependency>
  <groupId>com.zandero</groupId>
  <artifactId>rest.vertx</artifactId>
  <version>0.8.1-RC.1</version>
</dependency>
```
If a REST method returns a Future<Object> than a handler waits for the future to finish ... and returns the desired response.
The writer is determined according the future.result() type ... 

For instance: 
```java
@GET
@Path("async/{time}")
@ResponseWriter(GenericResponseWriter.class)
public Future<String> async(@Context Vertx vertx, @PathParam("time") int time) {
	Future<String> future = Future.future();
	slowService.async(vertx, future, time);
	return future;
}
```

Please give it a spin ...

**Comment by marcban** [comment]
thank you ! I will try to test it before the end of the week
