### ISSUE TITLE
mountSubRouter

### ISSUE THREAD

**Issue by dariolicci** [zandero/rest.vertx#92]
Hi,
I have this problem, in my Router extending RouterImpl, I add these paths:

route ("/ user / login"). handler (velocityHandler);
mountSubRouter ("/ api / v2", new RestBuilder (this) .register (UserRestapiController.class) .build ());

The problem is that the secondary router always works, either by executing the request /api/v2/user/login or /user/login, but it should only work for /api/v2/user/login

this is my UserRestapiController:

@Path ("/ user")
public class UserRestapiController {
     @GET
     @Path ("/:id")
     @Consumes ("application / json")
     public String get (@PathParam ("id") String id) {
         return "user id:" + id;
     }
}

regards
Dario

**Comment by dariolicci** [comment]
Hi,
I corrected my implementation with this change:
before: mountSubRouter ("/ api / v2", new RestBuilder (this) .register (UserRestapiController.class) .build ());
now: mountSubRouter ("/ api / v2", new RestBuilder (vertx) .register (UserRestapiController.class) .build ());

regards

**Comment by drejc** [comment]
Glad you made it work ... didn't even know this combination was possible ;)
