### ISSUE TITLE
About Interceptor

### ISSUE THREAD

**Issue by shuitai** [zandero/rest.vertx#95]
Please read the documentation ... 
you can either use the @PathParam or the @QueryParam annotations and there are a lot of additional options to deserialize the request.
Alternatively you can "join" the request and deserialize with @BeanParam ..
Depends on you use case.

_Originally posted by @drejc in https://github.com/zandero/rest.vertx/issues/90#issuecomment-739152656_

**Comment by shuitai** [comment]
I read then document many times...., because they cannot satisfy my requirement.
Because I want to use single reader handler to do uniform thing, then I can apply it in specific route path.

For example
@interceptor(AuditLog.class)
@get(value = "/getSADeviceById", produces = "application/json")
ApiResponse getDevice(@context context)

Currently, I used to do by guice interceptor(AuditLog.java)
I need to print the audit log in the route path, which will read the context information in method(getDevice), and print route information, parameters, headers.

If like you said, I will do a lot of duplicate thing for different route path.

ApiResponse getDevice1(@Header header, @PathParam("xxxxx") paramter, @context context) {
// duplicate code
System.out.println(header);
System.out.println(paramter);
}

ApiResponse getDevice2(@Header header, @PathParam("xxxxx") paramter, @context context) {
// duplicate code
System.out.println(header);
System.out.println(paramter);
}

ApiResponse getDevice3(@Header header, @PathParam("xxxxx") paramter, @context context) {
// duplicate code
System.out.println(header);
System.out.println(paramter);
}

But if there is interceptor, I only focus on my logic code.

@interceptor(AuditLog.class)
@get(value = "/getSADeviceById1", produces = "application/json")
ApiResponse getDevice1(@context context) {
}

@interceptor(AuditLog.class)
@get(value = "/getSADeviceById2", produces = "application/json")
ApiResponse getDevice2(@context context) {
}

@interceptor(AuditLog.class)
@get(value = "/getSADeviceById3", produces = "application/json")
ApiResponse getDevice3(@context context) {
}

**Comment by drejc** [comment]
There are multiple other ways to achieve this with vert.x handlers.
This is out of scope of this library
